parameters:
  - name: displayName
    type: string
  - name: terraformPath
    type: string

jobs:
- job: TerraformValidate
  displayName: '${{ parameters.displayName }}'
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ../steps/tf-install.yaml
  - template: templates/tests/terraform/allTests.yaml@azTemplates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}
