parameters:
  - name: serviceName
    type: string
  - name: terraformPath
    type: string

jobs:
- job: TerraformValidate${{ parameters.serviceName }}
  displayName: 'Validate ${{ parameters.serviceName }}'
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - template: ../steps/tf-install.yaml
  - template: templates/tests/terraform/allTests.yaml@azTemplates
    parameters:
      terraformPath: ${{ parameters.terraformPath }}
