trigger:
  - master
pr:
  - none

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/group-fixes
      endpoint: hmcts

parameters:
  - name: deployTo
    displayName: Services to Deploy (All default)
    type: string
    default: all-services
    values:
      - all-services
      - SharedInfra
      - SharedServies        

variables:
  - group: PIP-APIM-Common
  - name: product
    value: 'pip'
  - name: businessArea
    value: 'Cross-Cutting'
  - name: builtFrom
    value: $(Build.Repository.Name)
  - name: application
    value: 'publication-and-information'
  - name: terraformVersion
    value: '1.0.4'

stages:

  - stage: CIBuild
    displayName: 'CI Build Application'
    jobs:
      - template: pipeline/jobs/terraform-validate.yaml
        parameters:
          displayName: 'Validate Terraform files'

## NOTE: 
## The Environments and Services parameters below are duplicated
## This is due to limitations on AzDO Pipelines setting parameter templates and/or non-runtime parameters and/or object type variables.
## If you change one, be sure to change all others below.

  - template: pipeline/stages/plan.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'CIBuild'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'CIBuild'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'CIBuild'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'CIBuild'
      services: 
        - ${{ if or(eq(parameters.deployTo, 'all-services'), eq(parameters.deployTo, 'SharedInfra'))}}:
          - name: SharedInfra
            displayName: 'Shared Infrastructure'
            resourceGroupName: 'sharedinfra'
            resourcePrefix: 'pipapim'
            terraformVersion: ${{ variables.terraformVersion }}
        - ${{ if or(eq(parameters.deployTo, 'all-services'), eq(parameters.deployTo, 'SharedServies'))}}:
          - name: SharedServies
            displayName: 'Shared Services'
            resourceGroupName: 'sharedservices-state'
            resourcePrefix: 'pipss'
            terraformVersion: ${{ variables.terraformVersion }}

  - template: pipeline/stages/wait.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'
      services: 
        - ${{ if or(eq(parameters.deployTo, 'all-services'), eq(parameters.deployTo, 'SharedInfra'))}}:
          - name: SharedInfra
            displayName: 'Shared Infrastructure'
            resourceGroupName: 'sharedinfra'
            resourcePrefix: 'pipapim'
            terraformVersion: ${{ variables.terraformVersion }}
        - ${{ if or(eq(parameters.deployTo, 'all-services'), eq(parameters.deployTo, 'SharedServies'))}}:
          - name: SharedServies
            displayName: 'Shared Services'
            resourceGroupName: 'sharedservices-state'
            resourcePrefix: 'pipss'
            terraformVersion: ${{ variables.terraformVersion }}

  - template: pipeline/stages/apply.yaml
    parameters:
      environments:
        - name: sbox
          subscription: DTS-SHAREDSERVICES-SBOX
          dependency: 'CIBuild'
        - name: dev
          subscription: DTS-SHAREDSERVICES-DEV
          dependency: 'sbox'
        - name: test
          subscription: DTS-SHAREDSERVICES-TEST
          dependency: 'dev'
        - name: stg
          subscription: DTS-SHAREDSERVICES-STG
          dependency: 'test'
        - name: prod
          subscription: DTS-SHAREDSERVICES-PROD
          dependency: 'stg'
      services: 
        - ${{ if or(eq(parameters.deployTo, 'all-services'), eq(parameters.deployTo, 'SharedInfra'))}}:
          - name: SharedInfra
            displayName: 'Shared Infrastructure'
            resourceGroupName: 'sharedinfra'
            resourcePrefix: 'pipapim'
            terraformVersion: ${{ variables.terraformVersion }}
        - ${{ if or(eq(parameters.deployTo, 'all-services'), eq(parameters.deployTo, 'SharedServies'))}}:
          - name: SharedServies
            displayName: 'Shared Services'
            resourceGroupName: 'sharedservices-state'
            resourcePrefix: 'pipss'
            terraformVersion: ${{ variables.terraformVersion }}

