---
trigger:
  - master
pr:
  - none

parameters:
  - name: environments
    type: object
    default:
    - name: sbox
      subscription: DTS-SHAREDSERVICES-SBOX
    - name: dev
      subscription: DTS-SHAREDSERVICES-DEV
    - name: test
      subscription: DTS-SHAREDSERVICES-TEST
    - name: stg
      subscription: DTS-SHAREDSERVICES-STG
    - name: prod
      subscription: DTS-SHAREDSERVICES-PROD

variables:
  - group: PIP-APIM-Common
  - name: product
    value: 'pip'
  - name: businessArea
    value: 'Cross-Cutting'
  - name: builtFrom
    value: $(Build.Repository.Name)
  - name: application
    value: 'hearing-management-interface'

stages:

- ${{ each environment in parameters.environments }}:

  - stage: ${{ environment.name }}
    ${{ if environment.condition }}:
      condition: ${{ environment.condition }}
    displayName: Build ${{ environment.name }}
    variables:
      - group: PIP-APIM-BUILD-${{ upper(environment.name) }}

    jobs:
    - template: pipeline/jobs/setup-infra.yaml
      parameters:
        displayName: Set up infrastructure for APIM deployments
        subscription: ${{ environment.subscription }}
        environment: ${{ environment.name }}
        builtFrom: ${{ variables.builtFrom }}
        businessArea: ${{ variables.businessArea }}
        application: ${{ variables.application }}

    - job: Terraform
      displayName: 'printer'
      pool:
        vmImage: 'ubuntu-20.04'
      steps:
      - bash: |
          echo "la sub ${{ variables.log_analytics_subscription_id }}"
          echo "la v2 $[ variables.log_analytics_subscription_id ]"
          
    - template: pipeline/jobs/terraform.yaml
      parameters:
        displayName: Build Infrastructure with Terraform
        dependsOn: setupInfrastructure
        subscription: ${{ environment.subscription }}
        environment: ${{ environment.name }}
        resourceGroup: $(resourceGroup)
        storageAccount: $(storageAccount)
        containerName: $(containerName)
        builtFrom: ${{ variables.builtFrom }}
        product: ${{ variables.product }}
        laSubId: $[ variables.log_analytics_subscription_id ]
        variables:
          resourceGroup: $[dependencies.setupInfrastructure.outputs['setupResourceGroup.resourceGroup']]
          storageAccount: $[dependencies.setupInfrastructure.outputs['setupResourceGroup.storageAccount']]
          containerName: $[dependencies.setupInfrastructure.outputs['setupResourceGroup.containerName']]

    - template: pipeline/jobs/setup-azmonlink.yaml
      parameters:
        displayName: Set up Azure Monitor Link to Log Analytics
        dependsOn: Terraform
        subscription: ${{ environment.subscription }}
        environment: ${{ environment.name }}
        builtFrom: ${{ variables.builtFrom }}
        businessArea: ${{ variables.businessArea }}
